import { Fragment, useEffect } from 'react'
import Head from 'next/head'

import type { GetStaticProps, NextPage } from 'next'

import { Categories } from '../components/Categories'
import { Designs } from '../components/Designs'
import { Header } from '../components/Header'
import { Pagination } from '../components/Pagination'
import { Products } from '../components/Products'
import { Footer } from '../components/Footer'

import { FormattedDesign } from '../types/Design'
import { Category } from '../types/Category'
import { Product } from '../types/Product'

import { useDesign } from '../hooks/useDesign'
import { useCategory } from '../hooks/useCategory'
import { useProduct } from '../hooks/useProduct'

import { getDesigns } from '../data/getDesigns'

interface HomeProps {
  designs: FormattedDesign[]
  categories: Category[]
  products: Product[]
}

const Home: NextPage<HomeProps> = ({designs:designsCached}) => {
  const { designs, total, limit, page, handleChangePage, getDesigns } = useDesign()
  const { categories } = useCategory()
  const { products } = useProduct()

  useEffect(() => {
    getDesigns(designsCached)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <Fragment>
      <Head>
        <title>Tribalismo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Categories data={categories}/>

      <Products data={products}/>

      <Designs data={designs}/>

      <Pagination total={total} limit={limit} currentPage={page} goToPage={handleChangePage}/>

      <Footer />
    </Fragment>
  )
}

export default Home

export const getStaticProps:GetStaticProps = async () => {
  const designs = await getDesigns()

  return {
    props: {
      designs
    },
    revalidate: 60 * 60 * 60 * 24 //24 hours
  }
}